namespace FacebookTransactionParser
{
    internal class Constants
    {
        public static string FacebookFileName = "C2C_Order_History_Report";

        public static string Facebook = "Facebook";

        public static string MercariFileName = "Custom-sales-report";

        public static string Mercari = "Mercari";

        public static string GoogleImapHost = "imap.gmail.com";

        public static string GoogleSmtpHost = "smtp.gmail.com";

        public static int ImapPort = 993;

        public static int SmtpPort = 587;

        public static string SenderEmail = "fbtransactionparser@gmail.com";

        public static string EmailTemplate =
            "This is an autogenerated email containing useful information regarding your {0} transactions.<br/>This email is triggered on the first of the month.<br/>" +
            "Statement period: {1}<br/>" +
            "---------------------------------------------<br/>" +
            "Total revenue generated: {2}<br/>" +
            "Total sales tax generated: {3}<br/>" +
            "Total shipping charges: {4}<br/>" +
            "{5} sales fee: {6}<br/>" +
            "---------------------------------------------<br/>" +
            "Your take home profit: {7}<br/>" +
            "This data was generated from the provided file: {8}";
    }
}
